## Task 1:

### 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [16]:
def comp(x):
    try:
        c = 5/x
    except Exception as e: 
        print(e)
    else:
        print(c)

In [21]:
comp(3)
comp(0)

1.6666666666666667
division by zero


### 2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below. <br>
subjects=["Americans ","Indians"] <br>
verbs=["play","watch"]  <br>
objects=["Baseball","Cricket"] <br>

Output should come as below: <br>
Americans play Baseball. <br>
Americans play Cricket. <br>
Americans watch Baseball. <br>
Americans watch Cricket. <br>
Indians play Baseball. <br>
Indians play Cricket. <br>
Indians watch Baseball.<br>
Indians watch Cricket.<br>

In [34]:
subjects=["Americans ","Indians"] 
verbs=["play","watch"]  
objects=["Baseball","Cricket"]
l =[x.strip()+' '+y+' '+z+'.' for x in subjects for y in verbs for z in objects]
print(*l, sep='\n')

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


## Task 2:
### 1. Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.<br>
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [54]:
import numpy as np
ip = np.array([2,4,6,8]) 

def ATV(ipVect,n):
    opMat = np.column_stack([ipVect**(n-i-1) for i in range(n)])
    return opMat

print(ATV(ip,3))
    


[[ 4  2  1]
 [16  4  1]
 [36  6  1]
 [64  8  1]]
